name: Build and Debug Deploy to DigitalOcean (rsync debug)

on:
  push:
    branches:
      - main

env:
  DO_HOST: 139.59.30.89
  DO_USER: deployer
  DO_REMOTE_PATH: /var/www/upskill.gyannidhi.in/demo1
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Install helpers
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client

      - name: Configure SSH agent and add key (debug)
        run: |
          set -xe
          # write private key to a temp file
          printf '%s\n' "${{ secrets.DO_SSH_KEY }}" | sed 's/\r$//' > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          echo "Key file created: /tmp/deploy_key (size: $(stat -c%s /tmp/deploy_key) bytes)"
          # start ssh-agent & add key
          eval "$(ssh-agent -s)"
          ssh-add /tmp/deploy_key || true
          echo "List ssh-agent identities:"
          ssh-add -l || true
          # optionally show known_hosts lines when present (not printing secret)
          ls -la ~/.ssh || true

      - name: Quick SSH connectivity test (verbose)
        run: |
          set -xe
          SSH_PORT=${{ secrets.DO_PORT || '22' }}
          echo "Testing SSH connection to ${{ env.DO_USER }}@${{ env.DO_HOST }}:$SSH_PORT"
          # BatchMode avoids password prompts and causes fast failure on auth errors
          ssh -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p $SSH_PORT ${{ env.DO_USER }}@${{ env.DO_HOST }} 'echo SSH_OK' 

      - name: Rsync dry-run (diagnostic)
        run: |
          set -xe
          SSH_PORT=${{ secrets.DO_PORT || '22' }}
          echo "Running rsync dry-run (no changes) to show connectivity/auth"
          rsync -avz -n --delete -e "ssh -p $SSH_PORT -o StrictHostKeyChecking=no -o BatchMode=yes" ./dist/ ${{ env.DO_USER }}@${{ env.DO_HOST }}:${{ env.DO_REMOTE_PATH }}

      - name: (Actual Deploy) Deploy dist/ to DigitalOcean (uncomment when debugged)
        if: false
        run: |
          set -xe
          SSH_PORT=${{ secrets.DO_PORT || '22' }}
          rsync -avz --delete -e "ssh -p $SSH_PORT -o StrictHostKeyChecking=no" ./dist/ ${{ env.DO_USER }}@${{ env.DO_HOST }}:${{ env.DO_REMOTE_PATH }}
